steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "athena-core-api",
        "--source",
        ".",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--no-allow-unauthenticated",
      ]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
